config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :quotes
 
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
	validates :quote, presence: true, length: { minimum: 10 }
	validates :category, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	
	def index
  	@quotes = Quote.all
	end

	def show
    @quote = Quote.find(params[:id])
	end

	def new
	  @quote = Quote.new
	end
	 
	def edit
	  @quote = Quote.find(params[:id])
	end
	 
	def create
	  @quote = Quote.new(quote_params)
	 
	  if @quote.save
	    redirect_to quotes_path
	  else
	    render 'new'
	  end
	end

	def update
  	@quote = Quote.find(params[:id])
 
	  if @quote.update(quote_params)
	    redirect_to @quote
	  else
	    render 'edit'
	  end
	end

	def destroy
  	@quote = Quote.find(params[:id])
  	@quote.destroy
 
  	redirect_to quotes_path
	end
 
	private
	  def quote_params
	    params.require(:quote).permit(:quote, :author, :link, :category)
	  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with model: @quote, local: true do |form| %>

  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2>
        To save this quote, please correct the following
        <%= pluralize(@quote.errors.count, "error") %>
        :
      </h2>
      <ul>
        <% @quote.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='row'>
    <%= form.label :quote %>
    <%= form.text_area :quote %>
  </div>

  <div class='row'>
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class='row'>
    <%= form.label :link %>
    <%= form.url_field :link %>
  </div>

  <div class='row'>
    <%= form.label :category %>
  </div>
  <div class='row category-holder'>
    <div class='category-option'>
      <%= form.radio_button(:category, :everyday)%>
      <p>Everyday</p>
    </div>
    <div class='category-option'>
      <%= form.radio_button(:category, :religion)%>
      <p>Religion</p>
    </div>
    <div class='category-option'>
      <%= form.radio_button(:category, :travel)%>
      <p>Travel</p>
    </div>
    <div class='category-option'>
      <%= form.radio_button(:category, :career)%>
      <p>Career</p>
    </div>
  </div>

  <div class='row submit'>
    <%= form.submit %>
  </div>

<% end %>
<%= link_to 'Back to all', quotes_path %>

app/views/quotes/edit.html.erb
<div class='centered'>
    <div class="form">
        <h1>Edit quote</h1>
        <%= render 'form' %>
    </div>
</div>

app/views/quotes/index.html.erb
<div class='index'>
    <h1>Quotes for Life, Life in Quotes</h1>

    <div class='link-container'>
        <%= link_to 'Quote of the Day', root_path, class: "border-right" %>
        <%= link_to 'Add quote', new_quote_path %>
    </div>

    <div class='overflow'>
    <table>
      <tr>
        <th colspan="5"></th>
      </tr>

      <% @quotes.each do |quote| %>
        <tr>
          <td class='large'>"<%= quote.quote %>"</td>
          <td class='italic'> - <%= quote.author %></td>
          <td class='border-right'><%= link_to 'Edit', edit_quote_path(quote) %></td>
          <td><%= link_to 'Delete', quote_path(quote),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
    </div>
</div>

app/views/quotes/new.html.erb
<div class='centered'>
     <div class="form">
         <h1>Add a new quote</h1>
         <%= render 'form' %>
     </div>
 </div>

 <!-- .centered
   .form
     %h1 Add a new quote #{render 'form'} -->
 <!-- when I try to change this to haml, it tweaks the css... -->

app/views/quotes/show.html.erb
<div class='centered'>
    <div class='show'>
        <p>
          "
          <%= @quote.quote %>
          "
        </p>

        <% if @quote.author? %>
            <p>
              <strong>Author:</strong>
              <%= @quote.author %>
            </p>
        <% end %>

        <% if @quote.link? %>
            <p>
              <strong>Source:</strong>
              <%= @quote.link %>
            </p>
        <% end %>

        <p>
          <strong>Category:</strong>
          <%= @quote.category %>
        </p>

        <div class='link-container'>
        <%= link_to 'Edit', edit_quote_path(@quote), class: "border-right"%>
        <%= link_to 'Back to all', quotes_path %>
        </div>
    </div>
</div>

app/views/welcome/index.html.erb
<div class='welcome'>

    <% @focus_quote = Quote.last %>

    <h1 class="focus_quote">
      <%= @focus_quote.quote %>
      <% if @focus_quote.author? %>
        <span class="italic">
        - <%= @focus_quote.author %>
        </span>
       <% end %>
    </h1>

    <div class='link-container'>
        <%= link_to 'Show All', controller: 'quotes', class: 'border-right' %>
        <%= link_to 'Add quote', new_quote_path %>
    </div>
</div>